### ISSUE TITLE
Some specific details about the maf_bgzip tool

### ISSUE THREAD

**Issue by lumiratos** [csw/bioruby-maf#115]
Hello dear @csw and @pjotrp

As I mention before I am working in compression of MAF file and after installing your plugin I was trying to do some simulations. I am mainly using datasets from the goldenPath (http://hgdownload-test.sdsc.edu/goldenPath/) more specifically the ones that have the human specie as a reference (http://hgdownload-test.sdsc.edu/goldenPath/hg19/). After some test I did find that there are files that are no readable using your plugin. For example:

For this file (http://hgdownload-test.cse.ucsc.edu/goldenPath/hg18/multiz28way/maf/chrM.maf.gz) the maf_bgzip seem to work just fine:
`
lmatos@sapiens:~/jruby-1.7.11/bin$ ./maf_bgzip --dir ~/myTrash// --index --all -v --debug /media/ngs/luis/MAF/multiz28way/chrM.maf
DEBUG bio-maf: Created Bio::MAF::JThreadRunner set for 1 concurrent jobs.
DEBUG bio-maf: Processing chrM.maf.
DEBUG bio-maf: Running jobs.
DEBUG bio-maf: Using ThreadedChunkReaderWrapper.
DEBUG bio-maf: wrapping #<Method: Bio::MAF::Parser#parse_blocks_parallel> with []
DEBUG bio-maf: Starting parse worker.
DEBUG bio-maf: Starting read-ahead thread.
DEBUG bio-maf: Parse worker reached EOF.
 INFO bio-maf: Processed chrM.maf (0.5 MB) in 0s, 0.69 MB/s
 INFO bio-maf:   93 alignment blocks, average size 5.37 KB
 INFO bio-maf:   Compressed with BGZF (level=2) to 0.1 MB (0.3x)
DEBUG bio-maf: Finished processing.`

However for the multiz46way and multiz100way (http://hgdownload-test.sdsc.edu/goldenPath/hg19/) it seem that the plugin is not able to read the alignments for some reason:

`
lmatos@sapiens:~/jruby-1.7.11/bin$ ./maf_bgzip --dir ~/myTrash/lixo1/ --index --all -v --debug /media/ngs/luis/MAF/multiz46way/chrM.maf
DEBUG bio-maf: Created Bio::MAF::JThreadRunner set for 1 concurrent jobs.
DEBUG bio-maf: Processing chrM.maf.
DEBUG bio-maf: Running jobs.
ERROR bio-maf: Java::JavaUtilConcurrent::ExecutionException: java.util.concurrent.ExecutionException: org.jruby.exceptions.RaiseException: (Errno::ENOENT) /media/ngs/luis/MAF/multiz46way/chrM.maf
java/util/concurrent/FutureTask.java:252:in 'innerGet': java.util.concurrent.ExecutionException: org.jruby.exceptions.RaiseException: (Errno::ENOENT) /media/ngs/luis/MAF/multiz46way/chrM.maf
        from java/util/concurrent/FutureTask.java:111:in 'get'
        from java/lang/reflect/Method.java:616:in 'invoke'
        from /home/lmatos/jruby-1.7.11/lib/ruby/gems/shared/gems/bio-maf-1.0.1-java/lib/bio/maf/jobs.rb:94:in 'run'
        from /home/lmatos/jruby-1.7.11/lib/ruby/gems/shared/gems/bio-maf-1.0.1-java/bin/maf_bgzip:183:in '(root)'
        from org/jruby/RubyKernel.java:1101:in 'load'
        from ./maf_bgzip:23:in '(root)'
        from $_dot_/./maf_bgzip:23:in '(root)'
Caused by:
org/jruby/RubyFile.java:361:in 'initialize': org.jruby.exceptions.RaiseException: (Errno::ENOENT) /media/ngs/luis/MAF/multiz46way/chrM.maf
        from org/jruby/RubyIO.java:1178:in 'open'
        from /home/lmatos/jruby-1.7.11/lib/ruby/gems/shared/gems/bio-maf-1.0.1-java/lib/bio/maf/parser.rb:604:in 'initialize'
        from /home/lmatos/jruby-1.7.11/lib/ruby/gems/shared/gems/bio-maf-1.0.1-java/bin/maf_bgzip:83:in 'process_maf'
        from /home/lmatos/jruby-1.7.11/lib/ruby/gems/shared/gems/bio-maf-1.0.1-java/bin/maf_bgzip:77:in 'make_processing_task'
        from org/jruby/RubyProc.java:271:in 'call'
        from org/jruby/gen/InterfaceImpl1460228102.gen:13:in 'call'`

`
lmatos@sapiens:~/jruby-1.7.11/bin$ ./maf_bgzip --dir ~/myTrash/lixo1/ --index --all -v --debug /media/ngs/luis/MAF/multiz100way/chrM.maf
DEBUG bio-maf: Created Bio::MAF::JThreadRunner set for 1 concurrent jobs.
DEBUG bio-maf: Processing chrM.maf.
DEBUG bio-maf: Running jobs.
ERROR bio-maf: Java::JavaUtilConcurrent::ExecutionException: java.util.concurrent.ExecutionException: org.jruby.exceptions.RaiseException: (Errno::ENOENT) /media/ngs/luis/MAF/multiz100way/chrM.maf
java/util/concurrent/FutureTask.java:252:in 'innerGet': java.util.concurrent.ExecutionException: org.jruby.exceptions.RaiseException: (Errno::ENOENT) /media/ngs/luis/MAF/multiz100way/chrM.maf
        from java/util/concurrent/FutureTask.java:111:in 'get'
        from java/lang/reflect/Method.java:616:in 'invoke'
        from /home/lmatos/jruby-1.7.11/lib/ruby/gems/shared/gems/bio-maf-1.0.1-java/lib/bio/maf/jobs.rb:94:in 'run'
        from /home/lmatos/jruby-1.7.11/lib/ruby/gems/shared/gems/bio-maf-1.0.1-java/bin/maf_bgzip:183:in '(root)'
        from org/jruby/RubyKernel.java:1101:in 'load'
        from ./maf_bgzip:23:in '(root)'
        from $_dot_/./maf_bgzip:23:in '(root)'
Caused by:
org/jruby/RubyFile.java:361:in 'initialize': org.jruby.exceptions.RaiseException: (Errno::ENOENT) /media/ngs/luis/MAF/multiz100way/chrM.maf
        from org/jruby/RubyIO.java:1178:in 'open'
        from /home/lmatos/jruby-1.7.11/lib/ruby/gems/shared/gems/bio-maf-1.0.1-java/lib/bio/maf/parser.rb:604:in 'initialize'
        from /home/lmatos/jruby-1.7.11/lib/ruby/gems/shared/gems/bio-maf-1.0.1-java/bin/maf_bgzip:83:in 'process_maf'
        from /home/lmatos/jruby-1.7.11/lib/ruby/gems/shared/gems/bio-maf-1.0.1-java/bin/maf_bgzip:77:in 'make_processing_task'
        from org/jruby/RubyProc.java:271:in 'call'
        from org/jruby/gen/InterfaceImpl765126839.gen:13:in 'call'`

 I also tried from a different data set in this case where the reference is the mouse (http://hgdownload-test.sdsc.edu/goldenPath/mm10/multiz60way/maf/chrM.maf.gz). In this case the program was able to read the file without any problem as you can see in the following block:

`
lmatos@sapiens:~/jruby-1.7.11/bin$ ./maf_bgzip --dir ~/myTrash/lixo1/ --index --all -v --debug /media/ngs/luis/MAF/multiz60way/maf/chrM.maf
DEBUG bio-maf: Created Bio::MAF::JThreadRunner set for 1 concurrent jobs.
DEBUG bio-maf: Running jobs.
DEBUG bio-maf: Processing chrM.maf.
DEBUG bio-maf: Using ThreadedChunkReaderWrapper.
DEBUG bio-maf: wrapping #<Method: Bio::MAF::Parser#parse_blocks_parallel> with []
DEBUG bio-maf: Starting parse worker.
DEBUG bio-maf: Starting read-ahead thread.
DEBUG bio-maf: Parse worker reached EOF.
 INFO bio-maf: Processed chrM.maf (3.1 MB) in 2s, 1.40 MB/s
 INFO bio-maf:   403 alignment blocks, average size 7.78 KB
 INFO bio-maf:   Compressed with BGZF (level=2) to 0.6 MB (0.2x)
DEBUG bio-maf: Finished processing.`

The program seem also able to read files from the multiz17way dataset (http://hgdownload-test.sdsc.edu/goldenPath/mm8/multiz17way/chrY.maf.gz) as you can see in the following block:

`
lmatos@sapiens:~/jruby-1.7.11/bin$ ./maf_bgzip --dir ~/myTrash/lixo1/ --index --all -v --debug /media/ngs/luis/MAF/mm8/multiz17way/chrY.maf
DEBUG bio-maf: Created Bio::MAF::JThreadRunner set for 1 concurrent jobs.
DEBUG bio-maf: Processing chrY.maf.
DEBUG bio-maf: Running jobs.
DEBUG bio-maf: Using ThreadedChunkReaderWrapper.
DEBUG bio-maf: wrapping #<Method: Bio::MAF::Parser#parse_blocks_parallel> with []
DEBUG bio-maf: Starting parse worker.
DEBUG bio-maf: Starting read-ahead thread.
DEBUG bio-maf: Parse worker reached EOF.
 INFO bio-maf: Processed chrY.maf (10.6 MB) in 5s, 1.95 MB/s
 INFO bio-maf:   6216 alignment blocks, average size 1.75 KB
 INFO bio-maf:   Compressed with BGZF (level=2) to 2.7 MB (0.3x)
DEBUG bio-maf: Finished processing.`

Thanks very much for your attention

**Comment by lumiratos** [comment]
Regarding the output of the maf_bgzip I noticed that there are 2 files:
- the .kct file that contains the index information
- the .bgz file that should contain the alignment information of the previous index.

The bio_maf plugin does not have a tool to obtain the original MAF file using the .bgz and .kct files, am I rigth? As far as I know the goal of this plugin is to provide indexed and sequential access to MAF data an performing some manipulation in it. It is not have the capability of decoding a file am I correct dear @csw? Supposing that you want the original MAF file back. It is possible to obtain that using only the .bgz file?

Best regards

**Comment by lumiratos** [comment]
It seems that the chrM.maf file from the multiz46way and multiz100way are the only one that the maf_bgzip could not read. If we tried the chrY.maf the tool read the files just fine :P

**Comment by csw** [comment]
This doesn't appear to be a parser bug, exactly:

```
org.jruby.exceptions.RaiseException: (Errno::ENOENT) /media/ngs/luis/MAF/multiz46way/chrM.maf
from org/jruby/RubyIO.java:1178:in 'open'
```

ENOENT from an open() call indicates that the specified file was not found. Can you check the path with  ls or something? If your directory layout matches the multiz46way data set, chrM.maf should be in a 'maf' subdirectory, right?

**Comment by csw** [comment]
The .bgz file is a block-compressed gzipped version of the original MAF file, and perfectly readable with the normal gzip/gunzip tools; you could extract the uncompressed MAF data with `gzip -dc foo.bgz > foo.maf`. (However, it's compressed in chunks to enable random access, so plain old gzip won't give you a usable .bgz file for these purposes.)

**Comment by lumiratos** [comment]
Hello again dear @csw 

You were right. I did not read the error correctly. I was doing some quick tests yesterday and I was not able to read carefully the error message and I was also out of time. In fact I did have the files but they were compressed so the full name should be something like chrM.maf.gz.

If you do not mind I have some other questions regarding your implementation. First and according to the manual (http://csw.github.io/bioruby-maf/man/maf_bgzip.1.html) the maf_bgzip  read chucks up to 64 KB of uncompressed data. And it also said that each chuck contains an integer number of blocks except if a block is larger than 64 KB which means that the tool splits the information of the block into two consecutive chunks . Is that correct? I tried to extract the a .bgz file using gzip and it was extracted perfectly except the MAF header (lines that start with a #) where some line breaks were missing. 

My work is not regarding index access to these files. I am just working in compression. I am using a multi-thread approach, splitting the original uncompressed MAF file in several parts and compress each one independently. I am using ANSI C by the way. My approach  have a small problem because in order to estimate the offset to use in the fseek function to set the file positions for each part, I need the file in RAW format so I cannot use directly the compressed files in .maf.gz. I did noticed that your tool has an option to specify the number of concurrent jogs to run (number or threads). I was wondering how that works in more detail if the input file is compressed in .gz format. Your tool decompress the file to a temporary RAW file and then maf_bgzip uses this RAW file (uncompressed MAF file) to create the compressed chunks or your tool works differently?

I am using your tool in my research work and in a near future I will need to describe your tool with some detail. It is because of that that I am bothering you with all these question. I am sorry once again for the trouble and if there is some more documented information regarding this plugin like publications, technical reports, extended manuals or other kind of documents can you please share with me?

Thanks very much for you time

Best regards

**Comment by lumiratos** [comment]
I did notice that the maf_bgzip  tool outputs the total number of blocks read/compressed. Is there anyway to know how many chucks were used to compress the MAF file? I check the output log and it seems that this information is not outputted.

Thanks again dear @csw

**Comment by csw** [comment]
Hello @lumiratos, this discussion might be going a bit out of scope for a bug; feel free to email me directly.

The .bgz files I'm generating are in [BGZF](http://blastedbio.blogspot.com/2011/11/bgzf-blocked-bigger-better-gzip.html) format, and the underlying library I'm using (which I also wrote) is [bioruby-bgzf](https://github.com/csw/bioruby-bgzf). BGZF intrinsically uses a 64 KB chunk size, so larger records are indeed split into multiple BGZF chunks as needed. 

It sounds like BGZF may overlap quite a bit with the scheme you describe, and if you're not doing indexed access then there's no particular benefit to building the .kct indices or generating a BGZF version of the file. However, from your mention of `fseek` it sounds like you are doing some kind of random access; if that's the case, the BGZF 'virtual offset' scheme described in the link above, and used internally in my code, may be something you'd want to adopt.

The bio-maf parser can transparently read plain gzipped MAF files (i.e. .maf.gz); see [parser.rb:605](https://github.com/csw/bioruby-maf/blob/b9e5e75d5f41bb105d9edd12d30a4390c982c62d/lib/bio/maf/parser.rb#L605) for the gory details. These tools shouldn't require BGZF format for anything; you should be able to use uncompressed or 'normal' gzipped MAF files if that fits your workflow better.

The multithreaded processing differs depending on whether the parser is sequentially parsing an entire file or extracting specific blocks. Sequential parsing will use a single worker thread; see [Parser#parse_blocks_parallel()](https://github.com/csw/bioruby-maf/blob/b9e5e75d5f41bb105d9edd12d30a4390c982c62d/lib/bio/maf/parser.rb#L973). Random access parsing with `#fetch_blocks()` will distribute the work across the specified number of threads if possible; see `#fetch_blocks_merged_parallel()`.

I'm afraid the documentation for this may not be quite what you're looking for, but see:
- The [main documentation page](http://rubydoc.info/github/csw/bioruby-maf/)
- RubyDoc docs for the individual classes, e.g. [Bio::MAF::Parser](http://rubydoc.info/github/csw/bioruby-maf/Bio/MAF/Parser)
- [bioruby-bgzf](http://rubydoc.info/github/csw/bioruby-bgzf/master/frames) docs
- the [man pages](http://rubydoc.info/github/csw/bioruby-maf/#Command_line_tools)
- the [development blog](http://csw.github.io/bioruby-maf/)

**Comment by csw** [comment]
I don't quite have a hook in there for reporting the number of BGZF blocks, but it would be easy enough to add; you'd want to count the number of calls to [Bio::BGZF::Writer#write_buf()](https://github.com/csw/bioruby-bgzf/blob/7cffe7ffe4deb295c17877ab1c40645568f0b9e8/lib/bio-bgzf/writer.rb#L32) and expose that counter so `maf_bgzip` could read it.
