### ISSUE TITLE
Indexed access I/O code is misbehaving

### ISSUE THREAD

**Issue by csw** [csw/bioruby-maf#35]
This is NOT the expected I/O pattern for indexed access (from iosnoop):

```

  501 15159 R 228577696 262144       ruby ??/maf/chrY.maf
  501 15159 R 228578208 413696       ruby ??/maf/chrY.maf
  501 15159 R 228580656 634880       ruby ??/maf/chrY.maf
  501 15159 R 228581896 380928       ruby ??/maf/chrY.maf
  501 15159 R 228583368 262144       ruby ??/maf/chrY.maf
  501 15159 R 228583880 446464       ruby ??/maf/chrY.maf
  501 15159 R 228624896 602112       ruby ??/maf/chrY.maf
  501 15159 R 228626072 446464       ruby ??/maf/chrY.maf
  501 15159 R 228629232 602112       ruby ??/maf/chrY.maf
  501 15159 R 228632456 446464       ruby ??/maf/chrY.maf
  501 15159 R    33392   4096       ruby ??/<unknown (NULL v_parent)>/<unknown (NULL v_name)>
  501 15159 R 228633592 602112       ruby ??/maf/chrY.maf
  501 15159 R 228634768 446464       ruby ??/maf/chrY.maf
  501 15159 R 228694688 602112       ruby ??/maf/chrY.maf
  501 15159 R 228695864 446464       ruby ??/maf/chrY.maf
  501 15159 R 228748360 602112       ruby ??/maf/chrY.maf
  501 15159 R 228749536 1048576       ruby ??/maf/chrY.maf
  501 15159 R 228751584 413696       ruby ??/maf/chrY.maf
  501 15159 R 229707264  53248       ruby ??/maf/chrY.maf
  501 15159 R 229708304 208896       ruby ??/maf/chrY.maf
  501 15159 R 229708712 806912       ruby ??/maf/chrY.maf
  501 15159 R 231529048 1048576       ruby ??/maf/chrY.maf
  501 15159 R 231531096 1048576       ruby ??/maf/chrY.maf
  501 15159 R 231533144 626688       ruby ??/maf/chrY.maf
  501 15159 R 231535856 421888       ruby ??/maf/chrY.maf
  501 15159 R 231536680 593920       ruby ??/maf/chrY.maf
  501 15159 R 233264296 262144       ruby ??/maf/chrY.maf
  501 15159 R 233264808 696320       ruby ??/maf/chrY.maf
  501 15159 R 233275112 352256       ruby ??/maf/chrY.maf
  501 15159 R 233275800 696320       ruby ??/maf/chrY.maf
  501 15159 R 233697232 352256       ruby ??/maf/chrY.maf
  501 15159 R 228630408 1048576       ruby ??/maf/chrY.maf
  501 15159 R 231528536 262144       ruby ??/maf/chrY.maf
  501 15159 R 233697920 1048576       ruby ??/maf/chrY.maf
  501 15159 R 233699968 1048576       ruby ??/maf/chrY.maf
  501 15159 R 233702016 696320       ruby ??/maf/chrY.maf
  501 15159 R 233705152 352256       ruby ??/maf/chrY.maf
  501 15159 R 233705840 1048576       ruby ??/maf/chrY.maf
  501 15159 R 233707888 696320       ruby ??/maf/chrY.maf
  501 15159 R 234470736 352256       ruby ??/maf/chrY.maf
  501 15159 R 234471424 663552       ruby ??/maf/chrY.maf
  501 15159 R 234525120 262144       ruby ??/maf/chrY.maf
  501 15159 R 234525632 1048576       ruby ??/maf/chrY.maf
  501 15159 R 234527680 278528       ruby ??/maf/chrY.maf
  501 15159 R 234529696 770048       ruby ??/maf/chrY.maf
  501 15159 R 234531200 1048576       ruby ??/maf/chrY.maf
  501 15159 R 234533248 278528       ruby ??/maf/chrY.maf
  501 15159 R 234536112 278528       ruby ??/maf/chrY.maf
  501 15159 R 234537384 770048       ruby ??/maf/chrY.maf
  501 15159 R 234538888 1048576       ruby ??/maf/chrY.maf
  501 15159 R 234540936 278528       ruby ??/maf/chrY.maf
  501 15159 R 234542856 770048       ruby ??/maf/chrY.maf
  501 15159 R 234544360 245760       ruby ??/maf/chrY.maf
  501 15159 R 234555640 262144       ruby ??/maf/chrY.maf
  501 15159 R 234556152 1048576       ruby ??/maf/chrY.maf
  501 15159 R 234558200 139264       ruby ??/maf/chrY.maf
  501 15159 R 234559048 425984       ruby ??/maf/chrY.maf
  501 15159 R 234574944 262144       ruby ??/maf/chrY.maf
  501 15159 R 234599760 262144       ruby ??/maf/chrY.maf
  501 15159 R 234946176  81920       ruby ??/maf/chrY.maf
  501 15159 R 234993656 180224       ruby ??/maf/chrY.maf
  501 15159 R 235002912 262144       ruby ??/maf/chrY.maf
  501 15159 R 234534608 770048       ruby ??/maf/chrY.maf
  501 15159 R 235043424 1048576       ruby ??/maf/chrY.maf
  501 15159 R 235046120 1048576       ruby ??/maf/chrY.maf
  501 15159 R 235049448 1048576       ruby ??/maf/chrY.maf
  501 15159 R 235051496 1015808       ruby ??/maf/chrY.maf
  501 15159 R 235275928 262144       ruby ??/maf/chrY.maf
  501 15159 R 235276440 1048576       ruby ??/maf/chrY.maf
  501 15159 R 235278488 1048576       ruby ??/maf/chrY.maf
  501 15159 R 235280536  12288       ruby ??/maf/chrY.maf
  501 15159 R 235282416 1036288       ruby ??/maf/chrY.maf
  501 15159 R 235284440  12288       ruby ??/maf/chrY.maf
```

**Comment by csw** [comment]
Chunk size was not being set correctly. Fixing that has led to a new and exciting error:

```
/Users/csw/src/bioruby-maf/lib/bio/maf/parser.rb:289:in `parse_error': bad a line at: '9999999999>><<' (pos 1505 [17154048], last 8386906) (Bio::MAF::ParseError)
    from /Users/csw/src/bioruby-maf/lib/bio/maf/parser.rb:295:in `parse_block_data'
    from /Users/csw/src/bioruby-maf/lib/bio/maf/parser.rb:230:in `parse_block'
    from /Users/csw/src/bioruby-maf/lib/bio/maf/parser.rb:160:in `block (2 levels) in fetch_blocks_merged'
    from /Users/csw/src/bioruby-maf/lib/bio/maf/parser.rb:159:in `each'
    from /Users/csw/src/bioruby-maf/lib/bio/maf/parser.rb:159:in `block in fetch_blocks_merged'
    from /Users/csw/src/bioruby-maf/lib/bio/maf/parser.rb:149:in `each'
    from /Users/csw/src/bioruby-maf/lib/bio/maf/parser.rb:149:in `fetch_blocks_merged'
    from /Users/csw/src/bioruby-maf/lib/bio/maf/parser.rb:140:in `fetch_blocks'
    from /Users/csw/src/bioruby-maf/lib/bio/maf/index.rb:149:in `find'
    from bin/maf_extract_ranges_count:22:in `<main>'
```

**Comment by csw** [comment]
Added a `set_last_block_pos!` call in the appropriate place but it seems to be setting a last block position of 0:

```

  1) Bio::MAF::Parser#fetch_blocks with 1K chunk size behaves like any chunk size parses consecutive blocks further ahead
     Failure/Error: blocks = @p.fetch_blocks(fl)
     Bio::MAF::ParseError:
       invalid sequence line: s b at: 'ATGGG 
       s b>><<' (pos 1106 [6144], last 0)
     Shared Example Group: "any chunk size" called from ./spec/bio/maf/parser_spec.rb:171
     # ./lib/bio/maf/parser.rb:292:in `parse_error'
     # ./lib/bio/maf/parser.rb:325:in `rescue in block in parse_block_data'
     # ./lib/bio/maf/parser.rb:317:in `block in parse_block_data'
     # ./lib/bio/maf/parser.rb:306:in `each'
     # ./lib/bio/maf/parser.rb:306:in `parse_block_data'
     # ./lib/bio/maf/parser.rb:267:in `parse_block'
     # ./lib/bio/maf/parser.rb:163:in `block (2 levels) in fetch_blocks_merged'
     # ./lib/bio/maf/parser.rb:162:in `each'
     # ./lib/bio/maf/parser.rb:162:in `block in fetch_blocks_merged'
     # ./lib/bio/maf/parser.rb:151:in `each'
     # ./lib/bio/maf/parser.rb:151:in `fetch_blocks_merged'
     # ./lib/bio/maf/parser.rb:142:in `fetch_blocks'
     # ./spec/bio/maf/parser_spec.rb:146:in `block (4 levels) in <module:MAF>'
```

**Comment by csw** [comment]
Right, we're dealing with a tiny chunk read to hit an alignment boundary. See also #36.

```
       Parse error: found last block pos of 0 in: a score=185399.0
       s mm8.chr7                 80082592 121 + 145134094 GTGCTTATCTCGG
```

**Comment by csw** [comment]
Rethinking indexed parsing a bit. We have enough information to skip all this fragment joining nonsense at this point.

**Comment by csw** [comment]
Now it's behaving properly:

```

17:00:49.690356  read              F=5    B=0x1000                                              0.000002   ruby.6254372
17:00:49.690361  read              F=5    B=0x1000                                              0.000002   ruby.6254372
17:00:49.690374  read              F=5    B=0x1000                                              0.000002   ruby.6254372
17:00:49.690386  read              F=5    B=0x1000                                              0.000005   ruby.6254372
17:00:49.690408  read              F=5    B=0x1000                                              0.000002   ruby.6254372
17:00:49.690416  read              F=5    B=0x1000                                              0.000002   ruby.6254372
17:00:49.690428  read              F=5    B=0x1000                                              0.000004   ruby.6254372
17:00:49.690437  read              F=5    B=0x1000                                              0.000002   ruby.6254372
17:00:49.690447  read              F=5    B=0x1000                                              0.000002   ruby.6254372
17:00:49.690863  lseek             F=5    O=0x1199cd61         <SEEK_SET>                       0.000001   ruby.6254372
17:00:49.690868  read              F=5    B=0x29f                                               0.000003   ruby.6254372
17:00:49.690875  read              F=5    B=0x1000                                              0.000002   ruby.6254372
17:00:49.690887  read              F=5    B=0x1000                                              0.000002   ruby.6254372
17:00:49.690899  read              F=5    B=0x1000                                              0.000002   ruby.6254372
```
